name: lingobreeze_vocabulary
description: "LingoBreeze Vocabulary Feature"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.10.1 <4.0.0' # Note: Updated to standard range syntax for better compatibility

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.10.0
  cloud_firestore: ^6.0.1
  dio: ^5.9.0
  get: ^4.7.2
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true